name: Deploy Lambda via GitHub Actions

on:
  push:
    branches:
      - master  # change this if you deploy from a different branch

jobs:
  deploy-lambda:
    name: Deploy Lambda
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Zip Lambda function
        run: zip function.zip lambda_function.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::794038223971:role/githubrole2
          aws-region: us-east-1

      - name: Deploy or Update Lambda
        run: |
          FUNCTION_NAME=hello-github-lambda
          ROLE_ARN=arn:aws:iam::794038223971:role/lambda-basic-execution  # update if your Lambda role differs

          echo "Checking if Lambda function '$FUNCTION_NAME' exists..."
          if aws lambda get-function --function-name $FUNCTION_NAME > /dev/null 2>&1; then
            echo "Updating existing Lambda function..."
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --zip-file fileb://function.zip
          else
            echo "Creating Lambda function..."
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --runtime python3.9 \
              --role $ROLE_ARN \
              --handler lambda_function.lambda_handler \
              --zip-file fileb://function.zip
          fi
